export const JOB_ROLES = [
    "Software Developer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "UI/UX Designer",
    "QA Engineer",
    "DevOps Engineer",
    "System Administrator",
    "Data Analyst",
    "Business Analyst",
    "Project Manager",
    "Product Manager",
    "HR Executive",
    "HR Manager",
    "Accountant",
    "Finance Manager",
    "Sales Executive",
    "Sales Manager",
    "Marketing Executive",
    "Marketing Manager",
    "Customer Support Executive",
    "Operations Executive"
];