import express from 'express';
import { getAdminDashboard } from '../controller/dashboardController/adminDashboard/adminDashboard.js';
import { authorize } from '../middleware/authorizeRole.js';
import { authorization } from '../middleware/authMiddleware.js';
import { hrDashboard } from '../controller/dashboardController/HRDashboard/hrDashboard.js';
import { employeeDashboard } from '../controller/dashboardController/employeeDashboard/employeeDashboard.js';
const dashboardRouter=express.Router();
dashboardRouter.use(authorization);
dashboardRouter.get('/dashboard/admin',authorize('admin'),getAdminDashboard);
dashboardRouter.get('/dashboard/HR',authorize('HR'),hrDashboard);
dashboardRouter.get('/dashboard/employee',authorize('employee'),employeeDashboard);
export  default dashboardRouter;